{
 "title": "Public delegate dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Delegate stats", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 } },
  { "title": "Reward simulator", "type": "text", "gridPos": { "h": 1, "w": 11, "x": 13, "y": 0 }, "options": { "content": "<br/>s" } },
  {
   "title": "Delegate rank",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tbw_delegate{delegate=\"rank\"}",
     "legendFormat": "Delegate rank"
    }
   ]
  },
  {
   "title": "Block reward",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tbw_delegate{delegate=\"block_reward\"}) / sum(tbw_config{param=\"atomic\"})",
     "legendFormat": "Token"
    }
   ]
  },
  {
   "title": "Total forged block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tbw_delegate{delegate=\"forged_block\"})",
     "legendFormat": "Forged block"
    }
   ]
  },
  {
   "title": "Vote weight",
   "type": "stat",
   "description": "Amount of vote token",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tbw_delegate{delegate=\"voters_balance\"}) / sum(tbw_config{param=\"atomic\"})",
     "legendFormat": "With self votes"
    },
    {
     "expr": "sum(tbw_delegate{delegate=\"rl_voters_balance\"}) / sum(tbw_config{param=\"atomic\"})",
     "legendFormat": "Without self votes"
    }
   ]
  },
  {
   "title": "Voters rewards simulator",
   "type": "table",
   "description": "Reward simulation per balance divided in two parts :\n - new_vote: False,  if already voting\n - new_vote: True,  if this is for a new vote\n\nNew vote caculate the newer position of the delegate in order to adjust the DynamicReward",
   "gridPos": { "h": 34, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "tbw_reward_calc" }
   ]
  },
  {
   "title": "Block forging history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(tbw_delegate{delegate=\"forged_block\"})",
     "legendFormat": "Forged block"
    }
   ]
  },
  {
   "title": "Voters pending payout",
   "type": "stat",
   "description": "Total of token that will payed to voters",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tbw_payout{payout=\"pending_voters_payout\"}) / sum(tbw_config{param=\"atomic\"})",
     "legendFormat": "Token"
    }
   ]
  },
  {
   "title": "Block before payout",
   "type": "stat",
   "description": "Amount of blocks before the next payout",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tbw_payout{payout=\"block_before_payout\"}",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Payout block interval",
   "type": "stat",
   "description": "Number of processed blocks between two payouts",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tbw_config{param=\"payout_interval_block\"}",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Total voters rewards",
   "type": "stat",
   "description": "Total of distributed rewards to voters",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tbw_payout{payout=\"total_voters_rewards\"}) / sum(tbw_config{param=\"atomic\"})",
     "legendFormat": "token"
    }
   ]
  },
  {
   "title": "Voters list",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "tbw_voters" }
   ]
  },
  {
   "title": "Transaction history",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "tbw_transactions" }
   ]
  }
 ]
}